// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0fhlBMe0CJfUkJRcZwrT5edPxKkrl3Vc',
    appId: '1:277241069496:web:ce33e8cbcfcbc4342d594d',
    messagingSenderId: '277241069496',
    projectId: 'eduapp-db6d2',
    authDomain: 'eduapp-db6d2.firebaseapp.com',
    storageBucket: 'eduapp-db6d2.firebasestorage.app',
    measurementId: 'G-T5E20C7DVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm24ERJHZX9L1cGbrlBn3N7JWf6PsOmPg',
    appId: '1:277241069496:android:3d16d44cb5250e5f2d594d',
    messagingSenderId: '277241069496',
    projectId: 'eduapp-db6d2',
    storageBucket: 'eduapp-db6d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9WPt_qeWODe_oZd0vP1Uz7aU4kjGZkls',
    appId: '1:277241069496:ios:4018fe1d561f640d2d594d',
    messagingSenderId: '277241069496',
    projectId: 'eduapp-db6d2',
    storageBucket: 'eduapp-db6d2.firebasestorage.app',
    iosClientId: '277241069496-94j1trd2pql29j4q7ucavprbm1r811g9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9WPt_qeWODe_oZd0vP1Uz7aU4kjGZkls',
    appId: '1:277241069496:ios:4018fe1d561f640d2d594d',
    messagingSenderId: '277241069496',
    projectId: 'eduapp-db6d2',
    storageBucket: 'eduapp-db6d2.firebasestorage.app',
    iosClientId: '277241069496-94j1trd2pql29j4q7ucavprbm1r811g9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0fhlBMe0CJfUkJRcZwrT5edPxKkrl3Vc',
    appId: '1:277241069496:web:1fb17244d7d1bc332d594d',
    messagingSenderId: '277241069496',
    projectId: 'eduapp-db6d2',
    authDomain: 'eduapp-db6d2.firebaseapp.com',
    storageBucket: 'eduapp-db6d2.firebasestorage.app',
    measurementId: 'G-F2ZZJYS5K0',
  );

}